# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cwtCb4Xy5Gekg_qu2xKtYYIBaK-gYlEq
"""

import pandas as pd
import requests
import numpy as np
from IPython.display import display, HTML

class MarketIntelligenceEngine:
    def __init__(self):
        self.base_url = "https://api.coingecko.com/api/v3/coins/markets"

    def fetch_live_market_data(self) -> pd.DataFrame:
        params = {
            "vs_currency": "usd",
            "order": "market_cap_desc",
            "per_page": 40,
            "page": 1,
            "sparkline": "false"
        }
        try:
            response = requests.get(self.base_url, params=params, timeout=10)
            if response.status_code == 200:
                return pd.DataFrame(response.json())
            return pd.DataFrame()
        except Exception:
            return pd.DataFrame()

    def process_analytics(self, df: pd.DataFrame) -> pd.DataFrame:
        if df.empty:
            return df

        # Core Statistical Metric: Z-Score for price movement anomalies
        mean_delta = df['price_change_percentage_24h'].mean()
        std_delta = df['price_change_percentage_24h'].std()
        df['price_z_score'] = (df['price_change_percentage_24h'] - mean_delta) / std_delta

        # Volume-to-Market-Cap Efficiency Ratio
        df['volume_mcap_efficiency'] = df['total_volume'] / df['market_cap']

        return df

# Run Pipeline
engine = MarketIntelligenceEngine()
raw_df = engine.fetch_live_market_data()
processed_df = engine.process_analytics(raw_df)

if not processed_df.empty:
    # 1. Dashboard Metrics Summary
    avg_volatility = processed_df['price_change_percentage_24h'].std()
    max_gainer = processed_df['price_change_percentage_24h'].max()

    html_metrics = f"""
    <div style="font-family: Arial, sans-serif; padding: 15px; background-color: #111; border-radius: 8px; color: #fff;">
        <h2 style="color: #00ffcc; margin-bottom: 5px;">📊 Enterprise Market Intelligence & Analytics Engine</h2>
        <p style="color: #aaa; margin-top: 0;">Automated Data Pipeline & Real-Time Statistical Registry</p>
        <hr style="border: 0.5px solid #333;">
        <div style="display: flex; justify-content: space-between; margin-top: 15px;">
            <div><b>Assets Monitored:</b> <span style="color: #00ffcc;">{len(processed_df)}</span></div>
            <div><b>Highest 24h Gainer:</b> <span style="color: #11ff11;">{max_gainer:.2f}%</span></div>
            <div><b>Market Volatility (Std Dev):</b> <span style="color: #ffaa00;">{avg_volatility:.2f}</span></div>
        </div>
    </div>
    """
    display(HTML(html_metrics))

    # 2. Main Analytics Table
    print("\n- LIVE STATISTICAL REGISTRY ---")
    display_cols = ['name', 'current_price', 'market_cap', 'price_change_percentage_24h', 'price_z_score', 'volume_mcap_efficiency']
    formatted_df = processed_df[display_cols].copy()

    # Apply clean styling to the dataframe output
    styled_df = formatted_df.style.background_gradient(subset=['price_z_score'], cmap='coolwarm')\
                                   .format({'current_price': '${:,.2f}', 'market_cap': '${:,.0f}', 'price_change_percentage_24h': '{:.2f}%', 'price_z_score': '{:.2f}', 'volume_mcap_efficiency': '{:.4f}'})
    display(styled_df)

    # 3. Statistical Outliers
    print("\n- STATISTICAL OUTLIER DETECTION (Z-Score > |1.5|) ---")
    outliers = processed_df[processed_df['price_z_score'].abs() > 1.5]
    if not outliers.empty:
        display(outliers[['name', 'price_change_percentage_24h', 'price_z_score']].style.format({'price_change_percentage_24h': '{:.2f}%', 'price_z_score': '{:.2f}'}))
    else:
        print("No statistical anomalies detected in the current data window.")
else:
    print("[ERROR] Data pipeline execution halted. Verify API integration vector.")